#pragma config(Hubs,  S3, HTMotor,  HTServo,  none,     none)
#pragma config(Hubs,  S4, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     IR,             sensorI2CCustom)
#pragma config(Sensor, S2,     compass,        sensorI2CCustom)
#pragma config(Sensor, S3,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          signal,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          swimmer,       tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S3_C1_1,     arm,           tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S3_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C1_1,     x1,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C1_2,     x2,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C2_1,     y1,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C2_2,     y2,            tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Servo,  srvo_S3_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S3_C2_2,    pool,                 tServoStandard)
#pragma config(Servo,  srvo_S3_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S3_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S3_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S3_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c";
#include "MotorToServo.c";
#include "PolarDrive.c";
#include "3rd Party Sensor Drivers/drivers/hitechnic-compass.h";
#include "3rd Party Sensor Drivers/drivers/hitechnic-irseeker-v2.h";
#include "flushArm.c"

void initializeRobot(){
	servo[pool] = 0;
	nMotorEncoder[signal] = 0;
}

task main(){
	const float SPEEDRATIO = 0.7874;
	const float SPINRATIO = 0.2778;
	int joyx = 0;
	int joyy = 0;
	int joyAngle = 0;
	int finalAngle = 0;
	int compareAngle = 0;
	int joyHyp = 0;
	int spin = 0;
	int swimmerBtn = 0;

	initializeRobot();

	waitForStart();

	ClearTimer(T1);

	while(true){
		//Updates with the current joystick settings.
		getJoystickSettings(joystick);

		//Gets vector data concerning the driver's joystick, specifically the angle and hypotenuse.
		joyAngle = radiansToDegrees(atan2(joystick.joy1_y1,-joystick.joy1_x1));
		joyx = joystick.joy1_x1;
		joyy = joystick.joy1_y1;
		joyHyp = sqrt((joyx*joyx)+(joyy*joyy));
		joyHyp = joyHyp/(joy1Btn(7)+1);
		finalAngle = joyAngle - HTMCreadRelativeHeading(compass) - 45;

		if(joy1Btn(11)){
			compareAngle = ((joyAngle-90)%360) - (HTMCreadRelativeHeading(compass));
			if(compareAngle >= 180){compareAngle -= 360;}
			if(compareAngle < -180){compareAngle += 360;}
			nxtDisplayCenteredTextLine(3, "%d", joyAngle);
			nxtDisplayCenteredTextLine(4, "%d", HTMCreadRelativeHeading(compass));
			nxtDisplayCenteredTextLine(5, "%d", compareAngle);
			spin = compareAngle*SPINRATIO;
		}
		else{
			//map the right joystick value to spinning speed
			spin = joystick.joy1_x2*SPEEDRATIO;
		}

		if(joy1Btn(9)){
			joyHyp = flushBackup((nMotorEncoder[arm]/120) + 45,1.6);
			finalAngle = -135;
		}



		//this is the important actual movement function!
		polarDrive(x1, x2, y1, y2, joyHyp, finalAngle, spin);

		//Button Commands:

		//moves arm motor at 100 power for buttons "A" and "Y", and 50 power for "X" and "B"
		//both driver 1 and 2 share bucket control
		motor[arm] = joy1Btn(4)*100 + joy1Btn(3)*-100 + joy1Btn(1)*50 + joy1Btn(2)*-50 + joy2Btn(4)*100 + joy2Btn(3)*-100 + joy2Btn(1)*50 + joy2Btn(2)*-50 + joy1Btn(9)*100;

		//servo[spnr] = (joy2Btn(5)*128 + joy2Btn(7)*-128)+128;

		//hold LT the keep the panel up, release to let it go
		//servo[pool] = joy1Btn(7)*180;

		//uses D-Pad to drop blocks
		//up on D pad to scoop blocks
		//AKA set scoop to HIGH position
		if (joystick.joy1_TopHat == 4 || joystick.joy2_TopHat == 4 ){
			servo[pool] = 300;
		}

		//down on D pad to drop blocks
		//set scoop to LOW position
		if (joystick.joy1_TopHat == 0 || joystick.joy2_TopHat == 0){
			servo[pool] = 0;
		}


		//set scoop to middle position
		if (joystick.joy1_TopHat == 2 || joystick.joy1_TopHat == 6 || joystick.joy2_TopHat == 2 || joystick.joy2_TopHat == 6){
			servo[pool] = 127;
		}

		motor[motorE] = joy1Btn(5)*100 + joy1Btn(7)*(-100);
		//if LB, RB, and the START button is pressed, set the current robot forward as the driver forward
		if(joy1Btn(6) && !bSoundActive){
			nVolume = 4;
			PlaySound(soundUpwardTones);
			HTMCsetTarget(compass);
		}

		if(joystick.joy2_TopHat == 4){
			swimmerBtn = 1;
		}
		else{swimmerBtn = 0;}
		motor[swimmer] = 100*joy2Btn(6) + joy2Btn(8)*(-100) + swimmerBtn*100;

		if(time100[T1]/10 > 89) {
			if(time100[T1]/10 > 105){
				motor[signal] = 100;
			}
			else{
				moveTo(signal, 180, 50, 100, 4);
			}
		}

		if(!bSoundActive && nVolume != 1){
			nVolume = 1;
		}
	}
}
