#pragma config(Hubs,  S3, HTMotor,  HTServo,  none,     none)
#pragma config(Hubs,  S4, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     IR,             sensorI2CCustom)
#pragma config(Sensor, S2,     compass,        sensorI2CCustom)
#pragma config(Motor,  mtr_S3_C1_1,     arm,           tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S3_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C1_1,     x1,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C1_2,     x2,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C2_1,     y1,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C2_2,     y2,            tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Servo,  srvo_S3_C2_1,    spinner,              tServoStandard)
#pragma config(Servo,  srvo_S3_C2_2,    scoop,                tServoStandard)
#pragma config(Servo,  srvo_S3_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S3_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S3_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S3_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c";
#include "MotorToServo.c";
#include "PolarDrive.c";
#include "3rd Party Sensor Drivers/drivers/hitechnic-compass.h";
#include "3rd Party Sensor Drivers/drivers/hitechnic-irseeker-v2.h";
#include "flushArm.c"

task main()
{
	while(true){
		if (nNxtButtonPressed == 2){
			HTMCsetTarget(compass);
		}
		nxtDisplayCenteredTextLine(4, "> %d", HTIRS2readDCDir(IR));
		nxtDisplayCenteredTextLine(5, "> %d", HTMCreadRelativeHeading(compass));
	}
}
