#pragma config(Hubs,  S4, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S2,     compass,        sensorI2CHiTechnicCompass)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S4_C1_1,     xset1,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S4_C1_2,     xset2,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S4_C2_1,     yset1,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C2_2,     yset2,         tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c";

task main()
{
	const float SPEEDRATIO = 0.7874015748031496;
	int x = 0;
	int y = 0;
	int motorsx = 0;
	int motorsy = 0;
	float adjx = 0;
	float adjy = 0;
	float angle = 0;
float magnitude = 0;
	waitForStart();
	while(true){
		getJoystickSettings(joystick);
		x = joystick.joy1_x1;
		y = joystick.joy1_y1;
//this block rotates the joystick by 45 degrees, or pi/4
		if (x>0){
			angle = atan(y/x);
		}
		else {
			angle = 0;
		}
		angle = angle + PI/4;
		magnitude = sqrt(y^2 + x^2);
		adjx = magnitude*sin(angle);
		adjy = magnitude*cos(angle);
		x = adjx;
		y = adjy;
//end trogonometric section
		motorsx = x*SPEEDRATIO;
		motorsy = y*SPEEDRATIO;

		nxtDisplayCenteredTextLine(4, "%d", motorsx);
		nxtDisplayCenteredTextLine(5, "%d", motorsy);

		if (abs(motorsx) > 10){
			motor[xset1] = motorsx;
			motor[xset2] = motorsx;
		}
		else{
			motor[xset1] = 0;
			motor[xset2] = 0;
		}
		if (abs(motorsy) > 10){
			motor[yset1] = motorsy;
			motor[yset2] = motorsy;
		}
		else{
			motor[yset1] = 0;
			motor[yset2] = 0;
		}
	}

}
